### ISSUE TITLE
Support for AlloyUI 1.5.x

### ISSUE THREAD

**Issue by angelozerr** [angelozerr/tern-aui2.0.x#13]
See https://github.com/angelozerr/tern-aui1.5.x

**Comment by angelozerr** [comment]
@gamerson I have integrated AlloyUI 1.5.x inside tern.java.

See https://github.com/angelozerr/tern.java/issues/225

I have several problems like https://github.com/angelozerr/tern.java/issues/226 and https://github.com/angelozerr/tern-yui3/commit/c2f09bd5fa35f4c822516edfa612cafff8fb5d19 but in my case it works.

@gamerson @lilu1990 could you check please that AlloyUI 1.5.x and 2.0.x works for you.

It should be cool if you can test : 

 * create an new AlloyUI project (here extension point ternNature is used)
 * check/uncheck AlloyUI tern modules in teh Tern -> Modules properties page.

After that, could you check the order of the plugins .tern-project. It should be in this order  : 

```json
plugins":{"yui3":{},"aui1.5.x":{}}
```

yui3 must be declared before aui* otherwise it will not work (this issue was just for 1.5.x)

Thanks!

**Comment by lilu1990** [comment]
@angelozerr   sorry for the late reply , It works for me , both AlloyUI 1.5.x and 2.0.x are in the order yui before aui

**Comment by angelozerr** [comment]
> @angelozerr sorry for the late reply , It works for me 

Cool!

Is it working too inside JSP too? @gamerson seems having problem with that.

**Comment by gamerson** [comment]
After your pull it seems to be working again :) I'm not sure why that was
needed, unless something changed in 0.8 version of tern.java.

On Wed, Jan 21, 2015 at 4:01 PM, Angelo <notifications@github.com> wrote:

> @angelozerr <https://github.com/angelozerr> sorry for the late reply , It
> works for me
>
> Cool!
>
> Is it working too inside JSP too? @gamerson <https://github.com/gamerson>
> seems having problem with that.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/angelozerr/tern-aui2.0.x/issues/13#issuecomment-70798365>
> .
>



-- 
Greg Amerson
Liferay Developer Tools
Liferay, Inc. www.liferay.com

**Comment by angelozerr** [comment]
> After your pull it seems to be working again :)

That's cool!

@gamerson  @lilu1990  Note that we have created a release for tern.java 0.8.0. Now you must install http://oss.opensagres.fr/tern.repository/0.9.0-SNAPSHOT/
