### ISSUE TITLE
AlloyUI 1.5x with YUI3 will cause AlloyUI not able to use 

### ISSUE THREAD

**Issue by lilu1990** [angelozerr/tern-aui2.0.x#16]
when in a project has both AlloyUI 1.5x with YUI3 plugins , if I do code assist like 
AUI().use('aui-base',function(A){
new A. +(code assist)
})
the proposal is only in yui plugin  , AlloyUI 2.0x with YUI3 works fine 

![aui 1 5x yui3 0](https://cloud.githubusercontent.com/assets/4350803/5897997/b8eab982-a585-11e4-8c2c-71ddad5f9727.PNG)
![alloyui1 5x yui3 code assist](https://cloud.githubusercontent.com/assets/4350803/5898002/c402b694-a585-11e4-814f-994e3a3de3fa.PNG)

**Comment by angelozerr** [comment]
@lilu1990 that's very strange. Could you attach your trace with tern console please?

**Comment by lilu1990** [comment]
Nodejs Commnand: "D:\test run\eclipse folder\M6\eclipse_luna_m6\plugins\tern.eclipse.ide.server.nodejs.embed.win32.win32.x86_64_0.8.0.201501201310\node-v0.10.22-win32-x86_64\node.exe" "D:\test run\eclipse folder\M6\eclipse_luna_m6\plugins\tern.core_0.8.0.201501201310\node_modules\tern\bin\tern" --no-port-file
Project dir: D:\test run\eclipse folder\M6\eclipse_luna_m6\ws\ss
.tern-project: {"ide":{},"plugins":{"yui3":{},"aui1.5.x":{}}}
Server started at 61140 in 362ms
-----------------------------------
Tern request#: 
{"files":[{"name":"ss.js","text":"AUI().use('aui-base',function(A){\r\nnew A.ad\r\n})","type":"full"}]}

Tern response# with 129ms: 
{}
-----------------------------------
-----------------------------------
Tern request#type: 
{"query":{"type":"type","file":"ss.js","end":11,"docs":true,"urls":true,"types":true,"file":"ss.js"}}

Tern response#type with 14ms: 
{"type":"string","name":"string","url":"https://developer.mozilla.org/en-US/docs/JavaScript/Reference/Global_Objects/String","doc":"The String global object is a constructor for strings, or a sequence of characters."}
-----------------------------------
-----------------------------------
Tern request#: 
{"files":[{"name":"ss.js","text":"AUI().use('aui-base',function(A){\r\nnew A.ad\r\n})","type":"full"}]}
Tern response# with 8ms: 

-----------------------------------
{}
-----------------------------------
Tern request#completions: 
{"query":{"type":"completions","file":"ss.js","end":43,"types":true,"docs":true,"urls":true,"origins":true,"caseInsensitive":true,"lineCharPositions":false,"expandWordForward":false,"omitObjectPrototype":false,"file":"ss.js"}}

Tern response#completions with 17ms: 
{"start":41,"end":43,"isProperty":true,"isObjectKey":false,"completions":[{"name":"add","type":"fn(name: string, fn: fn(Y: yui.YUI, name: string), version: string, config?: yui.Object) -> yui.YUI","doc":"Registers a YUI module and makes it available for use in a `YUI().use()` call or\nas a dependency for other modules.\n\nThe easiest way to create a first-class YUI module is to use\n<a href=\"http://yui.github.com/shifter/\">Shifter</a>, the YUI component build\ntool.\n\nShifter will automatically wrap your module code in a `YUI.add()` call along\nwith any configuration info required for the module.","origin":"yui3"}]}
-----------------------------------

**Comment by angelozerr** [comment]
@lilu1990 Have you Plugin (from aui1.5) in your completion after A.?

**Comment by lilu1990** [comment]
sorry , do you mean aui 2.0 ?

**Comment by angelozerr** [comment]
> sorry , do you mean aui 2.0 ?

You should have this case : 

![aui15](https://cloud.githubusercontent.com/assets/1932211/5898646/bcaeb7b4-a551-11e4-9c38-074af545f159.png)

**Comment by lilu1990** [comment]
yeah I have that , but that's the only aui in the list , is it right ?

**Comment by angelozerr** [comment]
> yeah I have that , but that's the only aui in the list , is it right ?

No, you have ColorPicker for instance. I suppose that you are searching for AceEditor but if you see docs api http://alloyui.com/versions/1.5.x/api/ it doesn't appear because the JS code is not well annoted with yuidoc -(

**Comment by angelozerr** [comment]
@lilu1990 is my answer is OK? Can I close this issue?

**Comment by lilu1990** [comment]
yeah , please close it

**Comment by angelozerr** [comment]
> yeah , please close it

Ok thanks @lilu1990
