### ISSUE TITLE
Completion for Object literal config with inherit

### ISSUE THREAD

**Issue by angelozerr** [angelozerr/tern-aui2.0.x#18]
AceEditor extends Widget. The config of AceEditor Widget must inherit from teh Widget config. In other words : 

``` javascript
function(A) {
    new A.AceEditor(
      {
// here Ctrl+Space must show Widget config like boundingBox, height, etc
      }
    )
```

This issue will improve https://github.com/angelozerr/tern-aui2.0.x/issues/8

**Comment by angelozerr** [comment]
This feature was done for YUI3, AllyUI2 + AlloyUI 1.5.x. Demos + Test was added too.

**Comment by gamerson** [comment]
Thanks, verified this in latest tern.java 0.9.0-SNAPSHOT
